
/*This program uses a random number within a specified range and prompts the user to guess the number. It uses binary search logic to provide feedback and narrow down 
the possible range of numbers. The game continues until the user correctly guesses the number, and the total number of attempts is then displayed.*/

#include <iostream> //Allows input and output operations.
#include <cstdlib> //Provides functions involving memory allocation, rand(), etc.
#include <ctime> //Provides functions to work with time.

int guessTheNumber(int lowerBound, int upperBound) {
    // Generate a random number within the specified range
    int targetNumber = rand() % (upperBound - lowerBound + 1) + lowerBound;

    std::cout << "Welcome to Guess the Number Game!\n";
    std::cout << "I have selected a number between " << lowerBound << " and " << upperBound << ". Can you guess it?\n";

    int guess;
    int attempts = 0;

    do {
        std::cout << "Enter your guess: ";
        std::cin >> guess;
        attempts++;

        if (guess < targetNumber) {
            std::cout << "Too low! Try again.\n";
            lowerBound = guess + 1;
        } else if (guess > targetNumber) {
            std::cout << "Too high! Try again.\n";
            upperBound = guess - 1;
        } else {
            std::cout << "Congratulations! You guessed the correct number " << targetNumber << " in " << attempts << " attempts!\n";
        }

    } while (guess != targetNumber);

    return attempts;
}

int main() {
    
    /*time(0): The time function is part of the <ctime> header in C++. It returns the current time in seconds since the Epoch (January 1, 1970). 
    Passing 0 as the argument to time retrieves the current time.*/
    /*srand: The srand function is part of the <cstdlib> header in C++. It is used to seed the random number generator (rand() function).*/
    /*srand(time(0)): Seeds the random number generator with the current time. By using the current time as a seed, you ensure that the sequence of random numbers generated by rand() will be different each time you run the program.*/
    // Seed the random number generator with the current time
    srand(time(0));

    // Set the initial range for the game
    int lowerBound = 1;
    int upperBound = 100;

    int totalAttempts = guessTheNumber(lowerBound, upperBound);

    std::cout << "Game Over. Total attempts: " << totalAttempts << "\n";

    return 0;
}
